### ISSUE TITLE
conda command not found after running conda update package

### ISSUE THREAD

**Issue by mpesavento** [conda/conda#1364]
Using conda 3.10.1-py34_0 on OS10.10.3, I wanted to update one of our in-house packages, and so created the package appropriately, and ran:
$ conda update my-package

In this update, it found the new version of conda (3.13.0-py34_0), downloaded that and continued the update. The update failed in the package linking step, citing an "unexpected error". Further explorations after the crash revealed that the command 'conda' was no longer in anaconda/bin/
It does not seem like a good thing that rebuilding a package and updating conda in the process deletes the binary that actually does the updating and doesnt replace it.

My traceback is below.

---

Fetching package metadata: ......
Solving package specifications: .
Package plan for installation in environment /Users/mpesavento/anaconda:

The following packages will be downloaded:

| package | build |
| --- | --- |
| zeromq-4.0.5 | 0         451 KB |
| boto-2.38.0 | py34_0         1.4 MB |
| conda-env-2.2.0 | py34_0          21 KB |
| pyzmq-14.6.0 | py34_0         293 KB |
| requests-2.7.0 | py34_0         623 KB |
| 3scan-shared-0.4.1 | py34_6         171 KB |
| conda-3.13.0 | py34_0         172 KB |

```
------------------------------------------------------------
                                       Total:         3.1 MB
```

The following packages will be UPDATED:

```
3scan-shared: 0.4.0-py34_20 --> 0.4.1-py34_6 
boto:         2.37.0-py34_0 --> 2.38.0-py34_0
conda:        3.10.1-py34_0 --> 3.13.0-py34_0
conda-env:    2.1.4-py34_0  --> 2.2.0-py34_0 
pip:          6.1.1-py34_0  --> 7.0.3-py34_0 
pyzmq:        14.5.0-py34_0 --> 14.6.0-py34_0
requests:     2.6.0-py34_0  --> 2.7.0-py34_0 
setuptools:   15.0-py34_0   --> 17.0-py34_0  
zeromq:       4.0.4-0       --> 4.0.5-0      
```

Proceed ([y]/n)? 

Fetching packages ...
zeromq-4.0.5-0 100% |##################################################################################################| Time: 0:00:00 527.84 kB/s
boto-2.38.0-py 100% |##################################################################################################| Time: 0:00:00   1.69 MB/s
conda-env-2.2. 100% |##################################################################################################| Time: 0:00:00 252.09 kB/s
pyzmq-14.6.0-p 100% |##################################################################################################| Time: 0:00:00 388.10 kB/s
requests-2.7.0 100% |##################################################################################################| Time: 0:00:00   1.01 MB/s
3scan-shared-0 100% |##################################################################################################| Time: 0:00:00   1.21 MB/s
conda-3.13.0-p 100% |##################################################################################################| Time: 0:00:00 323.26 kB/s
Extracting packages ...
[      COMPLETE      ]|#####################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|#####################################################################################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the########################################                                       |  66%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/mpesavento/anaconda/bin/conda", line 5, in <module>
  File "/Users/mpesavento/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 202, in main
  File "/Users/mpesavento/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 207, in args_func
  File "/Users/mpesavento/anaconda/lib/python3.4/site-packages/conda/cli/main_update.py", line 40, in execute
  File "/Users/mpesavento/anaconda/lib/python3.4/site-packages/conda/cli/install.py", line 420, in install
  File "/Users/mpesavento/anaconda/lib/python3.4/site-packages/conda/plan.py", line 502, in execute_actions
  File "/Users/mpesavento/anaconda/lib/python3.4/site-packages/conda/instructions.py", line 141, in execute_instructions
  File "/Users/mpesavento/anaconda/lib/python3.4/site-packages/conda/instructions.py", line 84, in LINK_CMD
  File "/Users/mpesavento/anaconda/lib/python3.4/site-packages/conda/instructions.py", line 80, in link
  File "/Users/mpesavento/anaconda/lib/python3.4/site-packages/conda/install.py", line 523, in link
  File "/Users/mpesavento/anaconda/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
NotADirectoryError: [Errno 20] Not a directory: '/Users/mpesavento/anaconda/lib/python3.4/site-packages/KESMShared-0.4.1-py3.4.egg/EGG-INFO'

**Comment by asmeurer** [comment]
I'm assuming KESMShared comes from 3scan-shared.

**Comment by meawoppl** [comment]
Correct.  We can't have package names that start with 3 . . .

We had this problem on a windows machine as well.  @Geethree any additional information about this?

We suspect that this has to do with conda doing a self update when other packages are updated, ie conda is updating conda and conda-env without it being listed as a dependency in the meta.yaml.  

Related to #337 or  #1299 ?

Was solved only by complete reinstall of conda.  Yuck.

**Comment by ijstokes** [comment]
@asmeurer or @ilanschnell does this seem like a reasonable conclusion that conda being updated as part of other package updates might bork the entire conda install?  That seems "unexpected", and if it truly is the case then it seems like it is a high priority issue to get resolved.  "complete reinstall" sucks.  I've been there and done that.  Not Fun.  Does the Python 3.4 part have any bearing?

**Comment by meawoppl** [comment]
I did a little more reading, and this is highly related to this issue: https://github.com/conda/conda/issues/337  Especially comments from @pzwang and @teoliphant in that thread.

conda and conda-build are not even on that deps graph for that update, but still upgraded.

**Comment by modqhx** [comment]
@mpesavento @meawoppl Hey were you guys able to solve this issue? I'm having the exact same issue.. Everything was running fine until(maybe) I updated something and now conda command is not recognized at all. I have also tried adding the path to the .bash_rc file, still no luck :(

**Comment by zzstefan** [comment]
Yeah, I met the same question today. And I can'g open the launcher either

**Comment by scrudgey** [comment]
I think I have the same problem. I tried to update astropy and now "conda" is gone from the anaconda bin directory:

```
10657 ◯  ls ~/anaconda/bin | grep conda
conda-build
conda-convert
conda-develop
conda-index
conda-inspect
conda-metapackage
conda-pipbuild
conda-server
conda-skeleton
```

**Comment by modqhx** [comment]
I tried updating something, some package, now nothing can be found! 
`zsh: command not found: conda` :(

**Comment by ijstokes** [comment]
@modqhx take a look at https://github.com/conda/conda/issues/2911 for a technique that may recover things for you.  Note the comment that says after you've done this you should run `conda install conda`.

**Comment by kalefranz** [comment]
This is something *big* that we've fixed in 4.3.  Which we released to defaults today!!!

The best recovery method is to download the latest miniconda installer and install it on top of your current environment.

For OSX python 3.5, this would be something like

```
curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o ~/miniconda3.sh
bash ~/miniconda3.sh -bfp ~/anaconda
```

If you have conda installed in a `~/anaconda` directory.

**Comment by kalefranz** [comment]
Did you see that @ijstokes??!?  I finally got to hit the 'Close' button on this issue 😀

**Comment by ijstokes** [comment]
@kalefranz so to check what you're saying is the "fix borked conda" strategy is to install miniconda over top a busted Anaconda instance?  That is so awesome that this is finally fixed.  I can't tell you how many times I've destroyed Conda and had to go through rsync and similar contortions to try and recover my Anaconda installation...

**Comment by hashamMunir** [comment]
same issue I am having , I have tried all above possibilities but still no use. after running the miniconda same issue appears. conda not found. any help??

**Comment by jeevanel** [comment]
I tried what @kalefranz suggested, this fixed 'conda: command not found issue' but broke few other things. 

1. Now I cant import any of the libraries for example import numpy is failing too. 
2. If I try to run 
a. jupyter  I get  
"import jupyter_core.command
ModuleNotFoundError: No module named 'jupyter_core'"
or
b. IPython I get
"ModuleNotFoundError: No module named 'IPython'"

**Comment by adiprasad** [comment]
conda install -c conda-forge keras
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /Users/Ady/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    requests-2.13.0            |           py27_0         771 KB  conda-forge
    pbr-3.1.1                  |           py27_0         109 KB  conda-forge
    pyopenssl-16.2.0           |           py27_0          70 KB  conda-forge
    conda-4.3.29               |           py27_0         506 KB  conda-forge
    tensorflow-1.0.0           |           py27_0        32.0 MB  conda-forge
    keras-2.0.9                |           py27_0         441 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        33.9 MB

The following NEW packages will be INSTALLED:

    keras:      2.0.9-py27_0  conda-forge
    mock:       2.0.0-py27_0  conda-forge
    pbr:        3.1.1-py27_0  conda-forge
    protobuf:   3.4.0-py27_0  conda-forge
    tensorflow: 1.0.0-py27_0  conda-forge

The following packages will be UPDATED:

    conda:      4.2.13-py27_0 conda-forge --> 4.3.29-py27_0 conda-forge
    pyopenssl:  0.16.0-py27_0             --> 16.2.0-py27_0 conda-forge
    requests:   2.10.0-py27_0             --> 2.13.0-py27_0 conda-forge

Proceed ([y]/n)? y

Fetching packages ...
requests-2.13. 100% |###########################################################################################################################| Time: 0:00:01 504.38 kB/s
pbr-3.1.1-py27 100% |###########################################################################################################################| Time: 0:00:00 655.42 kB/s
pyopenssl-16.2 100% |###########################################################################################################################| Time: 0:00:00 505.44 kB/s
conda-4.3.29-p 100% |###########################################################################################################################| Time: 0:00:01 314.26 kB/s
tensorflow-1.0 100% |###########################################################################################################################| Time: 0:01:48 309.37 kB/s
keras-2.0.9-py 100% |###########################################################################################################################| Time: 0:00:02 212.77 kB/s
Extracting packages ...
[      COMPLETE      ]|##############################################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##############################################################################################################################################| 100%
Linking packages ...


CondaOSError: OS error: failed to link (src=u'/Users/Ady/anaconda/pkgs/protobuf-3.4.0-py27_0/lib/python2.7/site-packages/google/protobuf/internal/containers.pyc', dst='/Users/Ady/anaconda/lib/python2.7/site-packages/google/protobuf/internal/containers.pyc', type=1, error=OSError(17, 'File exists'))


-----------------------------------

conda missing in bin after this

Can anyone help?

**Comment by anapeleteiro** [comment]
Same problem for me, but installing a package request, and now conda is missing in bin, any help with this?

**Comment by habet700** [comment]
`
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2017.7.27.1|                0         152 KB  rpi
    libffi-3.2.1               |                0          47 KB  rpi
    ncurses-5.9                |                0         1.1 MB  rpi
    tk-8.6.6                   |                0         2.9 MB  rpi
    xz-5.2.2                   |                0         803 KB  rpi
    openssl-1.0.2l             |                0         2.8 MB  rpi
    readline-6.3               |                0         775 KB  rpi
    python-3.6.3               |       hea4cac4_0        18.5 MB  rpi
    asn1crypto-0.24.0          |   py36h5bc41d7_0         154 KB  rpi
    certifi-2017.11.5          |   py36h3c44272_0         195 KB  rpi
    chardet-3.0.4              |           py36_0         190 KB  rpi
    idna-2.6                   |           py36_0         121 KB  rpi
    pycosat-0.6.3              |   py36h8efb082_0         461 KB  rpi
    pycparser-2.18             |             py_0          85 KB  rpi
    pycrypto-2.6.1             |           py36_0         468 KB  rpi
    pyyaml-3.11                |           py36_0         360 KB  rpi
    six-1.11.0                 |   py36h1999902_0          20 KB  rpi
    urllib3-1.22               |           py36_0         154 KB  rpi
    cffi-1.11.2                |   py36he1ceefa_0         384 KB  rpi
    requests-2.18.4            |   py36h0397818_0          91 KB  rpi
    setuptools-38.4.0          |   py36hd934b87_0         524 KB  rpi
    cryptography-2.1.4         |   py36hf47e9ae_0         812 KB  rpi
    ruamel_yaml-0.11.14        |           py36_0         545 KB  rpi
    wheel-0.30.0               |   py36h76583d5_0          66 KB  rpi
    pip-9.0.1                  |           py36_0         1.7 MB  rpi
    pyopenssl-16.2.0           |           py36_0          72 KB  rpi
    conda-4.3.29               |   py36hb3d8718_0         514 KB  rpi
    ------------------------------------------------------------
                                           Total:        33.8 MB

The following NEW packages will be INSTALLED:

    asn1crypto:      0.24.0-py36h5bc41d7_0    rpi
    ca-certificates: 2017.7.27.1-0            rpi
    certifi:         2017.11.5-py36h3c44272_0 rpi
    cffi:            1.11.2-py36he1ceefa_0    rpi
    chardet:         3.0.4-py36_0             rpi
    cryptography:    2.1.4-py36hf47e9ae_0     rpi
    idna:            2.6-py36_0               rpi
    libffi:          3.2.1-0                  rpi
    ncurses:         5.9-0                    rpi
    pycparser:       2.18-py_0                rpi
    pyopenssl:       16.2.0-py36_0            rpi
    readline:        6.3-0                    rpi
    six:             1.11.0-py36h1999902_0    rpi
    tk:              8.6.6-0                  rpi
    urllib3:         1.22-py36_0              rpi

The following packages will be UPDATED:

    conda:           4.2.13-py34_0            rpi               --> 4.3.29-py36hb3d8718_0 rpi
    openssl:         1.0.1k-1                 None:///<unknown> --> 1.0.2l-0              rpi
    pip:             7.1.2-py34_0                               --> 9.0.1-py36_0          rpi
    pycosat:         0.6.1-py34_0             None:///<unknown> --> 0.6.3-py36h8efb082_0  rpi
    python:          3.4.3-1                  None:///<unknown> --> 3.6.3-hea4cac4_0      rpi
    requests:        2.7.0-py34_0             None:///<unknown> --> 2.18.4-py36h0397818_0 rpi
    ruamel_yaml:     0.11.14-py34_0           rpi               --> 0.11.14-py36_0        rpi
    setuptools:      18.1-py34_0                                --> 38.4.0-py36hd934b87_0 rpi
    wheel:           0.24.0-py34_0                              --> 0.30.0-py36h76583d5_0 rpi
    xz:              5.0.5-0                  None:///<unknown> --> 5.2.2-0               rpi

The following packages will be SUPERCEDED by a higher-priority channel:

    pycrypto:        2.6.1-py34_0             None:///<unknown> --> 2.6.1-py36_0          rpi
    pyyaml:          3.11-py34_1              None:///<unknown> --> 3.11-py36_0           rpi

Proceed ([y]/n)? y`


---- some installing ---

Installing rpi::pycparser-2.18-py_0 requires a minimum conda version of 4.3.###########################                                                                                       |  48%
wrk@1ace8ca85e21:~/files$ conda info
bash: /home/wrk/conda/bin/conda: No such file or directory


seems like a very similar problem here.

**Comment by travc** [comment]
The *exact* same thing that happened to Lukas (previous comment) just happened to me. 

Obviously needs a fix, but any suggestions on how to recover in the meantime?

**Comment by sudoerChris** [comment]
you can force install all other package before update, run the original install statement first to see what other package and their version to be installed
in my case:
`conda install ca-certificates=2018.8.24 libffi=3.2.1 xz=5.2.4 openssl=1.0.2r tk=8.6.8 python=
3.6.6 asn1crypto=0.24.0 certifi=2018.8.24 chardet=3.0.4 idna=2.7  pycosat=0.6.3 pycrypto=2.6.1 pysocks=1.6.8 pyyaml=3
.11 six=1.11.0 cffi=1.10.0 setuptools=40.2.0 cryptography=2.3.1 ruamel_yaml=0.11.14 wheel=0.31.1 pip=18.0  pyopenssl=
18.0.0 urllib3=1.23 requests=2.19.1  conda=4.5.11 --force`

then you can install pycparser successfully
p.s. cffi i used an older one instead of the recommended one because I think the old conda had a bug to process that, after update conda you can update cffi to latest one without problem
