### ISSUE TITLE
Unable to update or install anything due to missing menuinst and/or msvc_runtime package(s)

### ISSUE THREAD

**Issue by elakhna** [conda/conda#1877]
I keep getting:

```
Error: Could not open u'C:\\Users\\{USERNAME}\\.pkgs\\menuinst-1.2.2-py27_0.tar.bz2.part' for writing ([Errno 2] No such file or directory: u'C:\\Users\\{USERNAME}\\.pkgs\\menuinst-1.2.2-py27_0.tar.bz2.part').
```

or

```
Error: Could not open u'C:\\Users\\{USERNAME]\\.pkgs\\msvc_runtime-1.0.1-vc9_0.tar.bz2.part' for writing ([Errno 2] No such file or directory: u'C:\\Users\\{USERNAME}\\.pkgs\\msvc_runtime-1.0.1-vc9_0.tar.bz2.part').
```

Weirdly, both `menuinst` and `msvc_runtime` are listed as installed, but with a `[vc9]` next to them. Does this mean anything?

Regardless, I have tried reinstalling Anaconda and deleting every Conda-related folder (hidden and visible) in my Users folder, but nothing works. Help!!

**Comment by elakhna** [comment]
Anything? I'm not able to update or install any package, and reinstalling Conda doesn't help!!

**Comment by msarahan** [comment]
Please try deleting the ```C:\\Users\\{USERNAME}\\.pkgs``` folder.  That should be certain to clear up the two .part files, which come when things are not completely downloaded, or downloads fail.

**Comment by elakhna** [comment]
Hi Mike -- thank you for the response, but I deleted the ```.pkgs``` folder inside of ```Anaconda2``` in my user directory, but the same error happens. What else can I do?

**Comment by msarahan** [comment]
Next, my best guess is that this is a permissions issue.  Can you now create the ```C:\\Users\\{USERNAME]\\.pkgs\\``` folder?  Failing that, what is your username?  Does it have non-ascii characters?  I'm afraid we don't have much experience dealing with that situation.

**Comment by elakhna** [comment]
Mike -- I tried making a ```.pkgs``` folder, but I still get the error. I don't have any non-ASCII characters in my username, just a space between my first and last name. What's bizarre is that Conda used to work great until I reinstalled it recently. Is there a way to uninstall and delete every file/folder/reg key? Maybe that will work?

**Comment by msarahan** [comment]
If you have already tried uninstalling Anaconda or Miniconda and reinstalling them, then I don't think there's any more thorough way.

Spaces in usernames have been an issue in the past, and these issues come up now and again, particularly without CI for Windows watching to make sure that things stay fixed.  We'll try testing locally to reproduce your issue.

For now, can you try to create a new user and install Anaconda/Miniconda for that user?  It would be helpful actually to do this twice: once with a user that has a space in the name, and again with another account that does not.  Also, have you tried downloading a more recent installer?  Perhaps an issue was fixed in the meantime.

**Comment by kalefranz** [comment]
We're now testing conda with spaces, and we'll continue to.  We still don't recommend using spaces in paths though.
