### ISSUE TITLE
Fetching package metadata ....An unexpected error has occurred ( Installing psycopg2-2.6.2.tar.gz)

### ISSUE THREAD

**Issue by Sid-Dalal** [conda/conda#4667]
Getting this error while trying to install psycopg2-2.6.2.tar.gz package:

Fetching package metadata ....An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /home/sdalal/anaconda2  (writable)
    default environment : /home/sdalal/anaconda2
       envs directories : /home/sdalal/anaconda2/envs
          package cache : /home/sdalal/anaconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64  (offline)
                          https://repo.continuum.io/pkgs/free/noarch  (offline)
                          https://repo.continuum.io/pkgs/r/linux-64  (offline)
                          https://repo.continuum.io/pkgs/r/noarch  (offline)
                          https://repo.continuum.io/pkgs/pro/linux-64  (offline)
                          https://repo.continuum.io/pkgs/pro/noarch  (offline)
            config file : None
           offline mode : True
             user-agent : conda/4.3.8 requests/2.12.4 CPython/2.7.13 Linux/2.6.32-573.22.1.el6.x86_64 Red Hat Enterprise Linux Server/6.7 glibc/2.12
                UID:GID : 31146:5000

`$ ./conda install --offline /data2/TNFraud/psycopg2-2.6.2.tar.gz`

    Traceback (most recent call last):
      File "/home/sdalal/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/sdalal/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/home/sdalal/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/sdalal/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 210, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/home/sdalal/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 120, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/home/sdalal/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 445, in fetch_index
        repodatas = _collect_repodatas(use_cache, urls)
      File "/home/sdalal/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 433, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, urls)
      File "/home/sdalal/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 401, in _collect_repodatas_serial
        for url in urls]
      File "/home/sdalal/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 141, in func
        res = f(*args, **kwargs)
      File "/home/sdalal/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 385, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "/home/sdalal/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 191, in fetch_repodata_remote_request
        timeout=timeout)
      File "/home/sdalal/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/home/sdalal/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/sdalal/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "/home/sdalal/anaconda2/lib/python2.7/site-packages/conda/connection.py", line 70, in send
        raise RuntimeError(message)
    RuntimeError: EnforceUnusedAdapter called with url https://repo.continuum.io/pkgs/free/noarch/repodata.json.bz2
    This command is using a remote connection in offline mode.

**Comment by uudecode** [comment]
same problem with windows server 2012:

`PS C:\Users\root> conda install -c https://conda.anaconda.org/mvn cyavro
Fetching package metadata .....An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Anaconda3  (writable)
    default environment : C:\ProgramData\Anaconda3
       envs directories : C:\ProgramData\Anaconda3\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
           channel URLs : https://conda.anaconda.org/mvn/win-64
                          https://conda.anaconda.org/mvn/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.6.0 Windows/2012Server Windows/6.2.9200



`$ C:\ProgramData\Anaconda3\Scripts\conda-script.py install -c https://conda.anaconda.org/mvn cyavro`




    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 210, in install
       unknown=index_args['unknown'], prefix=prefix)
     File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 120, in get_index
       index = fetch_index(channel_priority_map, use_cache=use_cache)
     File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 445, in fetch_index
       repodatas = _collect_repodatas(use_cache, urls)
     File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 433, in _collect_repodatas
       repodatas = _collect_repodatas_serial(use_cache, urls)
     File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 401, in _collect_repodatas_serial
       for url in urls]
     File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 401, in <listcomp>
       for url in urls]
     File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 141, in func
       res = f(*args, **kwargs)
     File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 391, in fetch_repodata
       with open(cache_path, 'w') as fo:
   PermissionError: [Errno 13] Permission denied: 'C:\\ProgramData\\Anaconda3\\pkgs\\cache\\2116b818.json'
`

**Comment by kalefranz** [comment]
This is fixed in conda 4.3.13.

    conda update conda

If you continue to have problems, please *definitely* let me know.

**Comment by kalefranz** [comment]
Oh I'm sorry I read the stack trace wrong just now.  The problem is that conda can't find a cached copy of `https://repo.continuum.io/pkgs/free/noarch/repodata.json.bz2` in  your package cache, and it can't go out and get it from the internet because you're using `--offline` mode.  If you've used any `conda clean` commands, then `--offline` mode likely won't be possible.

The specific file in this case that conda is looking for is

    /home/sdalal/anaconda2/pkgs/cache/9ca791dd.json

**Comment by kalefranz** [comment]
CC @tyler-thetyrant another reason to get the `--offline` error correct :)

**Comment by TonyTangYu** [comment]
@kalefranz I run into the same error when I was trying to `conda create -n tensorflow python=3.6
`. I run `conda config --show-sources` and it gives me 
==> /home/cxt/.condarc <==
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
show_channel_urls: True
when I run CONDA_SSL_VERIFY=false conda update pyopenssl, the same error still happens.
Could you please fix this problem？
Thanks a lot.
