### ISSUE TITLE
Any Package Results in "CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/anaconda/linux-64/repodata.json> Elapsed: -"

### ISSUE THREAD

**Issue by Chaztikov** [conda/conda#6007]
Hi there,

Whatever package I try to install, I seem to get this error:

conda install -c anaconda accelerate 
Fetching package metadata ...
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/anaconda/linux-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(SSLError("Can't connect to HTTPS URL because the SSL module is not available.",),)

On another note, I have (un-/re-)installed many packages (such as curl) recently, could that be the issue? Must I reinstall anaconda?
Thanks

**Comment by Chaztikov** [comment]
This may be of use?

~$ conda config --show
add_anaconda_token: True
add_pip_as_python_dependency: True
allow_non_channel_urls: True
allow_softlinks: True
always_copy: False
always_softlink: False
always_yes: False
anaconda_upload: None
auto_update_conda: True
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: True
channels:
  - conda-forge
  - anaconda-fusion
  - pymks
  - defaults
client_ssl_cert: None
client_ssl_cert_key: None
clobber: False
create_default_packages: []
custom_channels:
  pkgs/free: https://repo.continuum.io/
  pkgs/pro: https://repo.continuum.io/
  pkgs/r: https://repo.continuum.io/
custom_multichannels:
  local: []
  defaults: ["https://repo.continuum.io/pkgs/free", "https://repo.continuum.io/pkgs/r", "https://repo.continuum.io/pkgs/pro"]
default_channels:
  - https://repo.continuum.io/pkgs/free
  - https://repo.continuum.io/pkgs/r
  - https://repo.continuum.io/pkgs/pro
disallow: []
envs_dirs:
  - /home/charles/anaconda3/envs
  - /home/charles/.conda/envs
force: False
json: False
local_repodata_ttl: 1
migrated_channel_aliases: []
offline: False
path_conflict: clobber
pinned_packages: []
pkgs_dirs:
  - /home/charles/anaconda3/pkgs
  - /home/charles/.conda/pkgs
proxy_servers: {}
quiet: False
remote_connect_timeout_secs: 9.15
remote_max_retries: 3
remote_read_timeout_secs: 60.0
rollback_enabled: True
shortcuts: True
show_channel_urls: None
ssl_verify: True
track_features: []
use_pip: True
verbosity: 0

**Comment by Chaztikov** [comment]
Also if I try to update:

~$ conda update anaconda

PackageNotInstalledError: Package is not installed in prefix.
  prefix: /home/charles/anaconda3
  package name: anaconda

**Comment by Chaztikov** [comment]
Also recent revisions:


2017-09-20 00:10:58  (rev 74)
     conda  {4.3.25 (anaconda) -> 4.3.23 (conda-forge)}
     conda-env  {2.6.0 (anaconda) -> 2.6.0 (conda-forge)}
     pytables  {3.3.0 -> 3.4.2 (conda-forge)}
     sfepy  {2017.1 (conda-forge) -> 2017.2 (conda-forge)}
    +biopandas-0.2.2 (conda-forge)
    +lzo-2.06

2017-09-21 02:48:59  (rev 75)
    -hdf5-1.8.18 (conda-forge)

2017-09-21 03:23:37  (rev 76)
     python  {3.5.3 -> 3.5.4 (conda-forge)}

2017-09-21 03:25:27  (rev 77)
    -argcomplete-1.0.0

2017-09-21 03:28:40  (rev 78)
    +argcomplete-1.8.2 (conda-forge)
    +conda-manager-0.4.0

2017-09-21 08:32:29  (rev 79)
    -openmpi-2.1.1 (conda-forge)

2017-09-21 09:31:32  (rev 80)
    -cmake-3.6.3

2017-09-21 10:13:46  (rev 81)
    -curl-7.54.1

2017-09-21 15:02:12  (rev 82)
    -anaconda-custom

2017-09-21 15:03:03  (rev 83)
    -pycurl-7.43.0

2017-09-21 17:17:26  (rev 84)
    -mpich2-1.4.1p1

**Comment by Chaztikov** [comment]
Finally, if I try to open anaconda-navigator:

anaconda-navigator
Traceback (most recent call last):
  File "/home/charles/anaconda3/bin/anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/home/charles/anaconda3/lib/python3.5/site-packages/anaconda_navigator/app/main.py", line 63, in main
    from anaconda_navigator.app.start import start_app
  File "/home/charles/anaconda3/lib/python3.5/site-packages/anaconda_navigator/app/start.py", line 30, in <module>
    from anaconda_navigator.widgets.main_window import MainWindow
  File "/home/charles/anaconda3/lib/python3.5/site-packages/anaconda_navigator/widgets/main_window.py", line 37, in <module>
    from anaconda_navigator.utils.analytics import GATracker
  File "/home/charles/anaconda3/lib/python3.5/site-packages/anaconda_navigator/utils/analytics.py", line 41, in <module>
    from anaconda_navigator.external.UniversalAnalytics import Tracker
  File "/home/charles/anaconda3/lib/python3.5/site-packages/anaconda_navigator/external/UniversalAnalytics/Tracker.py", line 28, in <module>
    from six.moves.urllib.request import (HTTPSHandler, Request, build_opener,
ImportError: cannot import name 'HTTPSHandler'

**Comment by kalefranz** [comment]
There is clearly something corrupted in your environment, possibly with the `requests` package, but also perhaps with one of `requests` dependencies. 

> On another note, I have (un-/re-)installed many packages (such as curl) recently, could that be the issue? Must I reinstall anaconda?

That would probably be the easiest solution.

**Comment by Mavuso** [comment]
Try conda config --set ssl_verify no

**Comment by camel315** [comment]
@Chaztikov Have you got this issue fixed? I got the same problem this week and could not figure it out. If you have the solution, please share your experience. Thank you.

**Comment by camel315** [comment]
@kalefranz I tried to reinstall anaconda without removing the existing conda, but it says I can only with -u to update it. This appears not to fix this. How can I totally remove anaconda? Like steps below?
conda install anaconda-clean 
anaconda-clean --yes
rm -rf ~/anaconda3
rm -rf ~/.anaconda_backup

Looking forward to your reply. Thank you

**Comment by kalpitsmehta** [comment]
@Mavuso What you suggested works. But is there any better way to do this without switching off SSL Verify?

**Comment by johnrogers1939** [comment]
Is this problem ever going to be resolved?  It or something very similar seems to have been around for some years.  I have tried Anaconda Navigator 1.6.9 & conda 4.3.30 & got this error both when attempting to create an environment & when attempting to install Rstudio.  conda config --set ssl_verify False turns off the SSL error messages but nothing more.  Navigator simply goes into a loop.

conda update conda fails with the SSL error.

**Comment by kalefranz** [comment]
You really need to keep your SSL stack up-to-date.  So

    conda update openssl ca-certificates certifi

and obviously probably have to switch ssl_verify off to make that happen.  Conda 4.4 does a better job at aggressively updating those packages for you.

**Comment by johnrogers1939** [comment]
Thanks for the effort, Kalefranz.  Unfortunately I still get an SSL error when I try the update - see attachment & note  ssl_verify is False.
![conda](https://user-images.githubusercontent.com/35214848/35415390-83c60460-0279-11e8-9622-a3d70f78ec2f.jpg)

I would upload conda 4.4 if I knew how to do it without using conda!

**Comment by sroder** [comment]
@Chaztikov @johnrogers1939 : 

Is it working for anyone? I am also facing this issue for sometime now. I do have hunch, maybe the firewall (comapany) is blocking the request update or my config file .condarc needs to be fixed

**Comment by johnrogers1939** [comment]
Hi 

I tried to download the update using Firefox & Firefox said the GitHub certificates were out of date.  If true, it would explain why we cannot update conda.

Cheers, John

**Comment by Chaztikov** [comment]
Apologies for the late response.  I'm very fond of Anaconda, but I used it
a bit recklessly  and ultimately added a new primary hard drive, and,
thereafter, reinstalled anaconda.

However, I'd recommend the following to avoid unintentional changes to your
system: you can simply add an alias to your bashrc that adds anaconda to
your path:

alias condapy='export PATH=/home/chaztikov/anaconda3/bin:$PATH'

to activate anaconda when needed (if that's applicable for your purposes).

**Comment by Chaztikov** [comment]
In short: sadly, I was not able to fix the problem, but have found a better
practice that seems to avoid this problem (I'll be back shortly, now that
I've said this...)

**Comment by siulkilulki** [comment]
I have the same problem. Anyone has a solution?

**Comment by sroder** [comment]
for me, this issue is resolved.
My system was behind a company firewall and I had to set proxy server in .condarc file

channels:
  - defaults
ssl_verify: true
proxy_servers:
  http: http://proxy_server:port
  https: https://proxy_server:port

if your proxy server takes username and password then mention that too

**Comment by Sandeepkosanam** [comment]
If there are any urls that are explicitly added in .condarc file , then there must be problem with those urls .Please make sure that you use the right proxies if you have any firewalls blocking ..
If you dont have any firewalls dont include any urls in that file

**Comment by Jaan987** [comment]
I had the same issue which due to a firewall as once I connected to a different wifi, everything connected and installed successfully.

**Comment by pdudero** [comment]
Well the issue is most definitely NOT resolved for me. I'm NOT behind any firewall. I had a working installation of conda, until I did a "conda update conda". Immediately after that I got this error. This happened once before, back in April or May. I had to completely uninstall Anaconda with all of the libraries I had collected, which took forever. And then reinstall from scratch. Since then I have been very careful NOT to "conda update conda", until today. So I'm not happy at the prospect of having to go through all that again, especially when the developers of conda apparently think that it's OUR problem.

Face it: the latest versions of conda are f'ed up. Please fix it.

**Comment by ashukrishna100** [comment]
I recently got this issue resolved. Use this command to see proxy_servers
`conda config --show`

If your any proxy server is present in the configuration. Kindly use
`conda config --remove-key proxy_servers'
It will remove saved proxy servers from anaconda configuration.
Enter
`conda clean --source-cache`
Now your http error is gone.
Give it a try and let me know in case of any difficulty.

**Comment by johnrogers1939** [comment]
There are dozens of complaints about this SSL problem which has been around for months if not years.  I have been looking at the conda code & conclude that it definitely because repo.continuum.io requires a CA certificate many of us do not have.  conda gets its CA certificate bundle from the user's browser (Mozilla Firefox in my case) &, presumably, in some cases the browser does not use the same certificate bundle as conda.  It seems to me that all would be well if GitHUb were to provide all the certificates we need - Windows certainly has a mechanism for installing them.
If & when I have time I shall try using a different browser to see if it solves the problem.

**Comment by jotes35** [comment]
I also have a similar issue. But in my case conda is installed on an HPC on which i am a user. I am able to create my environment and install libraries. But i was trying to install lxml and i had this issue.

**Comment by rigvedepur** [comment]
> Try conda config --set ssl_verify no

Solved for me

**Comment by rmxhhh** [comment]
Is there any solutions for Windows?I have the same problem when i want to install  caffe's dependency package.
`
(caffe) C:\Users\Administrator>conda install --yes cmake ninja numpy scipy protobuf==3.1.0 six scikit-image pyyaml pydotplus graphviz
Solving environment: failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/willyd/noarch/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(MaxRetryError('HTTPSConnectionPool(host=\'conda.anaconda.org\', port=443): Max retries exceeded with url: /willyd/noarch/repodata.json (Caused by SSLError(SSLError("bad handshake: Error([(\'SSL routines\', \'ssl3_get_server_certificate\', \'certificate verify failed\')],)",),))',),)
`

**Comment by ewascent** [comment]
Are there installation and debugging tools for this project?

**Comment by ewascent** [comment]
I had this issue with SSL enabled behind a firewall and disabled with no firewall. So proxy settings are only part of the issue. When I run sudo /Users/r633878/miniconda3/bin/conda update openssl ca-certificates certifi the command succeeds, when run as a sudoer. So access to some cache or cert store is possibly another issue.

**Comment by InsomniumBR** [comment]
I have this problem and I JUST have this problem when using the 64 bit package. So, definitively having a proxy server is not my problem. If I install the 32 bit version I can successfully do the command below. 

`conda create --name opencv-env python=3.6
`
But If I am using the 64 bit version:

```
C:\WINDOWS\system32>conda create --name opencv-env python=3.6
Solving environment: failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/free/win-64/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available."))'))

And I need to use the 64 bit version for using dlib with CUDA.
```

**Comment by albjoaov** [comment]
I'm still getting this problem. There's any official solution for this? (Without disabling the SSL verify, because the documentation says that it's not recommended and does not work for me either)

**Comment by wenboyang214** [comment]
uninstall then re-install solve it for me.

**Comment by InsomniumBR** [comment]
@wenboyang214
Another day I reinstalled it 9 times trying to figure out.
This is not the problem.
There’s a problem on the 64bit package. The 32bit works well. Same machine, same network.

**Comment by InsomniumBR** [comment]
Disabling the SSL didn’t worked for me either.

**Comment by Vampire-Vx** [comment]
Also has the same problem and disable SSL not work for me.

**Comment by aaronlelevier** [comment]
Same here... seems like a timeout setting for https://conda.anaconda.org won't let long downloads work

**Comment by bashtip** [comment]
Same problem. No solution worked yet. Tried different networks...Is there already a solution?

**Comment by johnrogers1939** [comment]
How does one do that, please?  John

**Comment by mohan-barathi** [comment]
I made a workaround using the channel
`conda-forge`
instead of using `https://conda.anaconda.org/*` 
I was lucky that all the packages i required were available in this `conda-forge` channel. 😃
others can give a try..!

**Comment by troxsm** [comment]
Had this issue on win10. This resolved it for me:
https://github.com/conda/conda/issues/6064#issuecomment-453147166

**Comment by noyessie** [comment]
Use conda included promp ( not the system cli ) solve problems for me.

**Comment by adrian-moisa** [comment]
On windows 10 use "Anaconda Prompt"

**Comment by zoidgerd** [comment]
Using the Anaconda Prompt worked for me too! Thanks!

**Comment by mmw5hy** [comment]
Anaconda Prompt solved for me as well

**Comment by wilocw** [comment]
I solved this error when using the Windows 10 CLI (```cmd.exe```) by adding `%ANACONDAPATH%\Library\bin` to the path variable, since it's not always convenient to use Anaconda Prompt.

Thus the relevant directories to add to the environment paths:
```
%ANACONDAPATH%;
%ANACONDAPATH%\Scripts;
%ANACONDAPATH%\Library\bin;
```

**Comment by Bacchusm** [comment]
After adding the path you need to reboot you computer.  Once I did that it work for me.   Thank You

**Comment by mingwandroid** [comment]
> since it's not always convenient to use Anaconda Prompt.

If convenience is more important to you than correctly functioning software then this is fine. Always activate your conda envs please! There are a number of ways of doing that. Anaconda Prompt, Anaconda Navigator or running the activate script yourself. Adding to PATH doesn't activate conda envs.

**Comment by osubou** [comment]
On windows 10 use "Anaconda Prompt"   it work

**Comment by tk1363704** [comment]
> On windows 10 use "Anaconda Prompt"

Anoconda Prompt works for me too! Thank you!

**Comment by mdrehan4all** [comment]
Just open Anaconda Navigator > Select  Your Environment (if created) > Open Terminal > Now Try Again

**Comment by gitjoop** [comment]
> Just open Anaconda Navigator > Select Your Environment (if created) > Open Terminal > Now Try Again

This works for me while all others do not. Why does this work on contrast to opening a anaconda command prompt manually and activate that environment?

**Comment by ericzhu1990** [comment]
for those who have tried everything above and still no luck, check if you have multiple pythons mapped. In my case I uninstalled Python 2.7 (anaconda was in 3.7) and everything worked smoothly. Python 2.7 is going to be deprecated soon so I figure there is no harm removing it from my computer.

**Comment by bbrannon4** [comment]
I've tried all suggestions with no luck, though I may have multiple versions installed.  I just tried to uninstall everything, but a version of Python2.7 with anaconda3 still shows up in my installed programs, but it won't uninstall because it can't find the exe, and I can't find the files anywhere on my C drive.  I ignored that and completely reinstalled anaconda 64bit first, and then uninstalled and tried 32 bit, but no luck with either.  I did have to add the paths mentioned to my env variables to use hte command prompt, but now I get the same error there as I do in the anaconda prompt or through the navigator.  I know I have a few other unrelated pieces of software that have their own versions of python installed - maybe this is an issue?

**Comment by jainayush007** [comment]
What is %ANACONDAPATH% ?

> I solved this error when using the Windows 10 CLI (`cmd.exe`) by adding `%ANACONDAPATH%\Library\bin` to the path variable, since it's not always convenient to use Anaconda Prompt.
> 
> Thus the relevant directories to add to the environment paths:
> 
> ```
> %ANACONDAPATH%;
> %ANACONDAPATH%\Scripts;
> %ANACONDAPATH%\Library\bin;
> ```

What would be %ANACONDAPATH% here? Can you please tell the exact command? Also, I dont see a 32-bit download available for anaconda. I am on windows 10 and struggling with the same issue.

**Comment by wilocw** [comment]
> What is %ANACONDAPATH% ?
 
`%ANACONDAPATH%` refers to the directory that you have Anaconda installed to, e.g. I have it installed to `C:\Program Files\Anaconda3\`. This is dependent on where you have installed it. According the Anaconda installation documentation [[link]](https://docs.anaconda.com/anaconda/install/windows/), the default path from the installer would be `C:\Users\[username]\Anaconda3\`.

> Also, I dont see a 32-bit download available for anaconda.

It doesn't seem to appear by default on the Download page (though I am on a Ubuntu machine atow), but if you click explicitly click the "Windows", there should be a link to "32-bit Graphical Installer".

The direct download link taken from there is 
`https://repo.anaconda.com/archive/Anaconda3-2018.12-Windows-x86.exe`

**Comment by Exlsunshine** [comment]
> Use conda included promp ( not the system cli ) solve problems for me.

works for me.

**Comment by jainayush007** [comment]
Thanks.That worked!

**Comment by daynefiler** [comment]
Can anyone explain why this issue was closed? None of the solutions have worked for me, and no one has given an actual explanation of the problem.

**Comment by msarahan** [comment]
It's closed because the original issue was different from most of the recently reported problems.  The original issue was a certificate problem on Linux.  The recently reported problems are Windows.  That specific issue has been discussed at length at https://github.com/conda/conda/issues/8046

The problem is that when conda's base environment is not activated, there's a high likelihood that it will not be able to find its openssl library.  Many tools that use conda don't use activation, and they've been breaking badly.  Activation of the base env puts the correct PATH entries in place, so it works (barring any library conflicts from other people putting conflicting openssl DLLs into System32).

We think we have a fix for this in https://github.com/conda/conda/pull/8287.  We'll be releasing conda 4.6.6 with this code into the conda-canary channel later today.

**Comment by daynefiler** [comment]
@msarahan thank you for the response. Just for clarification — I am having this issue on Linux and changing the ssl permissions did not fix the problem.

**Comment by msarahan** [comment]
Please just open a new issue with all of the requested info in the issue template.  This one is too mixed up with other stuff, and it'll be better to have a clean slate.  Please reference this issue, though.

**Comment by jayakumarselvan** [comment]
After googling i got the solution for windows.
Ignore the _windows cmd_. Use **anaconda prompt**. It’s working.
[Ref...](http://www.probeqa.com/condahttperror-http-000-connection-failed/)

**Comment by kurikabocya** [comment]
using "dependency walker", i checked "c:\programdata\anaconda3\dlls\_ssl.pyd.
and found that it depends on c:\windows\system32\lbssl-1_1-x64.dll and
                                                 c:\windows\system32\lbcrypto-1_1-x64.dll.
After removing those two files, problem solved.

_ssy.pyd should depend on  c:\programdata\anaconda3\library\bin\lbssl-1_1-x64.dll and
                                                 c:\programdata\anaconda3\library\bin\lbcrypto-1_1-x64.dll.

**Comment by rajeshp2408** [comment]
Issue Getting SSL error:
conda update conda -- FAILED
Error: CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/win-64/repodata.json.bz2>

Found the solution: 
For windows 10, there is already OpenSSL. Just add the following path and it should fix the issue:

- C:\Users\<username>\Anaconda3\Scripts
- C:\Users\<username>\Anaconda3\
- C:\Users\<username>\Anaconda3\Library\bin    -- This is the directory for openssl

Hope this helps.

**Comment by msarahan** [comment]
Conda 4.6.7 included code to help this issue for conda itself: https://github.com/conda/conda/pull/8287

If you still see this problem, here's what to try:

1. use anaconda prompt (in your start menu).  This activates your base environment, which should allow you to update to the new conda
2. always activate your environments.  Without activation, the correct entries may not be on PATH, and that's why you see this error, as many have noted.  We have more info on activation in our docs at https://conda.io/activation

**Comment by kurikabocya** [comment]
---information add--
c:\windows\system32\libssl-1_1-x64.dll and 
c:\windows\system32\libcrypto-1_1-x64.dll
these two dlls lacks some method which 
c:\programdata\anaconda3\dlls\_ssl.pyd requires.

c:\programdata\anaconda3\library\bin\libssl-1_1-x64.dll and
c:\programdata\anaconda3\library\bin\libcrypto-1_1-x64.dll
have every method  which 
c:\programdata\anaconda3\dlls\_ssl.pyd requires.

**Comment by Alireza-Amiri** [comment]
Thank you for your help and comment. I learned alot.
I installed Anaconda Navigator on my mac version 10.14.3. Every-time that i start to create a file in environments i face this error:
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/r/noarch/repodata.json.bz2><br>Elapsed: -<br><br>An HTTP error occurred when trying to retrieve this URL.<br>HTTP errors are often intermittent, and a simple retry will get you on your way.<br><br>If your current network has https://www.anaconda.com blocked, please file<br>a support request with your network engineering team.<br><br>SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/r/noarch/repodata.json.bz2 (Caused by SSLError(SSLError("bad handshake: Error([(\'SSL routines\', \'tls_process_server_certificate\', \'certificate verify failed\')])")))'))<br>
I read most of the comments of this page but i couldn't find a way.
Any help and suggestion would be highly appreciated.
Best,
Alireza

**Comment by edgarbasto** [comment]
> Had this issue on win10. This resolved it for me:
> [#6064 (comment)](https://github.com/conda/conda/issues/6064#issuecomment-453147166)

Also worked for me.

**Comment by KonstantinKlepikov** [comment]
> I solved this error when using the Windows 10 CLI (`cmd.exe`) by adding `%ANACONDAPATH%\Library\bin` to the path variable, since it's not always convenient to use Anaconda Prompt.
> 
> Thus the relevant directories to add to the environment paths:
> 
> ```
> %ANACONDAPATH%;
> %ANACONDAPATH%\Scripts;
> %ANACONDAPATH%\Library\bin;
> ```

100% problem with PATH in win, and it is first pretendent for checking solutions - creating right record for path

**Comment by muhark** [comment]
Have tried all of the above fixes still having issues in Linux (Fedora 28).  Might be worth noting that pip has ceased to work in my base environment (could it be an issue with pip in some cases?) Will try doing a clean install of anaconda, but it'd be nice not to have this since I will have to re-build my environments.

**Comment by mdegans** [comment]
> > I solved this error when using the Windows 10 CLI (`cmd.exe`) by adding `%ANACONDAPATH%\Library\bin` to the path variable, since it's not always convenient to use Anaconda Prompt.
> > Thus the relevant directories to add to the environment paths:
> > ```
> > %ANACONDAPATH%;
> > %ANACONDAPATH%\Scripts;
> > %ANACONDAPATH%\Library\bin;
> > ```
> 
> 100% problem with PATH in win, and it is first pretendent for checking solutions - creating right record for path

You're supposed to be able to install and use Anaconda without modifying path. I'm getting this error on a fresh, fully updated, windows install and there are no firewall policies prohibiting outgoing connections. I'm just not going to bother with Anaconda support, i guess. To those disabling ssl to get around this error: that's a really bad idea.

**Comment by msarahan** [comment]
> You're supposed to be able to install and use Anaconda without modifying PATH

We agree completely.  The problem is that a lot of 3rd party software implemented "conda support" without really asking us, and they didn't include all the PATH stuff that they needed to.  We describe more about this at https://conda.io/activation

**Comment by msarahan** [comment]
Also, more in https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#ssl-connection-errors

**Comment by mdegans** [comment]
> > You're supposed to be able to install and use Anaconda without modifying PATH
> 
> We agree completely. The problem is that a lot of 3rd party software implemented "conda support" without really asking us, and they didn't include all the PATH stuff that they needed to. We describe more about this at https://conda.io/activation

Understandable, but I'm not trying to install any third party software. I'm trying to create a new Conda environment after a fresh install of both Windows and Miniconda. Specifically, the command that was run was:

`Conda C:\Users\insertuserhere\Miniconda3\Scripts\conda.exe create -p C:\Users\insertuserhere\Miniconda3\envs\projectname-y python=3.7`

Which raises ...`CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/free/noarch/repodata.json.bz2>`...

**Comment by msarahan** [comment]
Are you using Anaconda Prompt?  It doesn't look like it.  Please read the links I posted. 
 There are reasons why that doesn't work.  In conda 4.6.8, we've tried to make absolute path calls like yours work, but it's pretty hacky.  The only way we actually support is using activation.  Any other way might work, but you're on your own.

**Comment by mdegans** [comment]
> Are you using Anaconda Prompt? It doesn't look like it. Please read the links I posted.
> There are reasons why that doesn't work. In conda 4.6.8, we've tried to make absolute path calls like yours work, but it's pretty hacky. The only way we actually support is using activation. Any other way might work, but you're on your own.

I'm not using Anaconda Prompt because the command is being launched through PyCharm. I would modify the system PATH, but that would have the consequence of possibly breaking other things. Disabling SSL is also something I'm not comfortable doing. It's a shame it doesn't work now since I used this procedure before and it did.

**Comment by msarahan** [comment]
Try setting this env var:

CONDA_DLL_SEARCH_MODIFICATION_ENABLE

With a value of 1. Our python interpreter adds more paths when you enable that. We call it "hacktivation". It might help with finding openssl. It will only work with our latest python builds. It will not work if your python package comes from conda forge or anywhere else.

https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#numpy-mkl-library-load-failed

**Comment by mdegans** [comment]
Thanks for the suggestion, but `CONDA_DLL_SEARCH_MODIFICATION_ENABLE=1` doesn't work for me, unfortunately. I can add a conda env from the Anaconda Prompt with `conda create -n test` and it activates with `conda activate test`, but when I do it this way, it's not visible to PyCharm as an existing environment in interpreter settings.

The only way I can get it to work is by manually selecting python.exe in the env as the interpreter after installing some dependency. So far this seems to work, but attempts to install additional dependencies after the fact from within PyCharm fail with the same error message, so i have to go in and out of the Anaconda Prompt (or use pip). Is calling conda.exe with the full path really unsupported?

**Comment by MuqadderIqbal** [comment]
> 
> 
> I recently got this issue resolved. Use this command to see proxy_servers
> `conda config --show`
> 
> If any proxy server is present in the configuration. Kindly use
> `conda config --remove-key proxy_servers`. It will remove saved proxy servers from anaconda configuration.
> Enter
> `conda clean --source-cache`
> Now your http error is gone.
> Give it a try and let me know in case of any difficulty.

Looks like conda clean --source-cache is depricated in latest version of anaconda. They suggest using this instead:

conda build purge-all

**Comment by Yurzs** [comment]
For windows users
Even if you've downloaded and installed 64 bit version of conda you need to install 32(!) bit version of OpenSSL

**Comment by yumy-yumy** [comment]
I came up with the same problem. After waiting for a moment, I retried and it worked.

**Comment by VictorOchieng** [comment]
Came across the CondaHTTP Connection error after installing Anaconda environment on a new Windows 10 computer.  I tried virtually all the recommendations above unsuccessfully!  Looking up the Anaconda archives, I downloaded the immediate previous release  .... and on installation and rebooting my PC, all is now well.
![condahttperror](https://user-images.githubusercontent.com/4420962/55168850-84a0ec00-516b-11e9-9c8e-118b71ba9924.png)

**Comment by VictorOchieng** [comment]
One more thing... remember to  include the following in your Path Variable....

D:\Anaconda3;
D:\Anaconda3\Scripts;
D:\Anaconda3\Library\bin

Most people tend to only add the first two ... as captured here.... https://github.com/pypa/virtualenv/issues/1139#issuecomment-467705899

**Comment by BradXiao** [comment]
Try installing OpenSSL.
https://slproweb.com/products/Win32OpenSSL.html

**Comment by MuqadderIqbal** [comment]
Installing/reinstalling OpenSSL didn't resolve the CondaHTTP connection errors for me. However, I noticed that if I try to do a "conda update..." from a *regular* command shell, I get these errors. However, if I do the same "conda update..." via the Anaconda Prompt shell (in admin mode), everything works just fine and updates happen as expected. 

Can someone try to replicate this and confirm? I'm on Windows 10 with latest Anaconda installation.

**Comment by br7roy** [comment]
> After googling i got the solution for windows.
> Ignore the _windows cmd_. Use **anaconda prompt**. It’s working.
> [Ref...](http://www.probeqa.com/condahttperror-http-000-connection-failed/)

it's work for me.
thx!

**Comment by simone-viozzi** [comment]
Same issue, i forgot to add the "anaconda3\Library\bin" to the path. Add that path and reboot.

**Comment by ludiusvox** [comment]
Mine was my 5G network when I switched back to the 2.4ghz it started working again.

**Comment by ctivanovich** [comment]
Mine was due to using Astrill VPN. I have to add python.exe as an excluded application if I want the VPN running while I install packages with conda.

**Comment by Jaguar100** [comment]
Hi. I'm also getting "### CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/r/noarch/repodata.json.bz2>".  **Nothing Works**

I cannot install packages or update conda or any existing packages. I've tried the following from this and other posts - though some I am unable to do because I don't know how (indicated below). I am an analytics guy so not super familiar with Command line code. **No luck with anything.** I am on a corporate network with a firewall and using the Navigator Prompt. **Can someone please help me!** Does it come down to me needing a proxy server or path of a certificate bundle from my network admin? Thanks ahead of time!

- OpenSSL: No luck. I don't have the required Admin rights to install this app.

- Proxy Server and Cache Cleaning approach @MuqadderIqbal: No luck.

- Adding environment paths: have not tried this as I don't know how to change the paths

- conda config --set ssl_verify no (& "false): Neither worked

- Update the condarc file: I don't know how to do this. So could not due the following as someone recommend:
       channels:
                     defaults
                     ssl_verify: true
                     proxy_servers:
                     http: http://proxy_server:port
                     https: https://proxy_server:port

- Activate Environments: I do not understand how to do this.

- pip install --trusted-host pypi.org: ERROR: You must give at least one requirement to install (see "pip help install")

**Comment by whungt** [comment]
> Issue Getting SSL error:
> conda update conda -- FAILED
> Error: CondaHTTPError: HTTP 000 CONNECTION FAILED for url https://repo.anaconda.com/pkgs/main/win-64/repodata.json.bz2
> 
> Found the solution:
> For windows 10, there is already OpenSSL. Just add the following path and it should fix the issue:
> 
> * C:\Users<username>\Anaconda3\Scripts
> * C:\Users<username>\Anaconda3\
> * C:\Users<username>\Anaconda3\Library\bin    -- This is the directory for openssl
> 
> Hope this helps.

This resolved my problem on win7.

**Comment by bituritesh** [comment]
@kalefranz  thanks a lot sir. conda update openssl ca-certificates certifi worked like a magic.  👍

**Comment by Jaguar100** [comment]
Thanks @whungt. How does one add paths in command line as you recommend
above?

**Comment by whungt** [comment]
@Jaguar100 Please refer to [this page](https://web.archive.org/web/20150729183638/http://www.itechtalk.com/thread3595.html) to add the above three directories into the Path variable.

**Comment by NandhanThiravia** [comment]
Here is the solution for the HTTP Error and the SSL Error:
1) Add the proxy details in .condarc
2) Disable SSL Verify

.condarc file content
------------------------
ssl_verify: False
channels:
  - defaults
proxy_servers:
    http: http://<uname:passwd>@<ip:port>
    https: https://<uname:passwd>@<ip:port>

**Comment by theycallmefm** [comment]
Hello, I am working on Ubuntu 16.04 to create a conda environment and I get this error. It is very similar to this issue. I tried answers which were posted on here, but still no luck. There aren't any proxy servers set in my conda and I am using latest version. I've been working on this for a long time, any help would be appreciated!

`CondaHTTPError: HTTP 000 CONNECTION FAILED for url <http://conda/release/linux-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError("HTTPConnectionPool(host='conda', port=80): Max retries exceeded with url: /release/linux-64/repodata.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f742c2ebc18>: Failed to establish a new connection: [Errno -2] Name or service not known'))"))`

**Comment by spigeli** [comment]
Conda init worked for me

**Comment by prbans** [comment]
Tried all of the above steps, this is still broken

WARNING: The conda.compat module is deprecated and will be removed in a future release.
Collecting package metadata: failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/noarch/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(MaxRetryError('HTTPSConnectionPool(host=\'conda.anaconda.org\', port=443): Max retries exceeded with url: /conda-forge/noarch/repodata.json (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available."))'))

**Comment by PritishSehzpaul** [comment]
> 
> 
> Try setting this env var:
> 
> CONDA_DLL_SEARCH_MODIFICATION_ENABLE
> 
> With a value of 1. Our python interpreter adds more paths when you enable that. We call it "hacktivation". It might help with finding openssl. It will only work with our latest python builds. It will not work if your python package comes from conda forge or anywhere else.
> 
> https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#numpy-mkl-library-load-failed

@msarahan 's answer solved the problem for me. Thank you. Do look at the link he provided for understanding what is really happening. 
In my case, I had copied libssl-1_1.dll and libcrypto-1_1.dll to C:\Windows\System32 while trying to run libcurl on windows along with their x64 dlls. This I believe caused the error because soon after removing them and fresh installing openssl the error was gone. 

Install openssl from -
https://slproweb.com/products/Win32OpenSSL.html
(PS: I would recommend installing Win32 installer even if you have 64-bit architecture)

Also, install openssl in it's own directory and add that to path instead of installing the dlls in C:\Windows\System32

**Comment by ashendes** [comment]
An update of conda worked for me.

> _conda update conda_

**Comment by huangbxaaa** [comment]
I just try to change the channel of conda and it works

**Comment by earthstrider** [comment]
conda config --set ssl_verify false

**Comment by PritishSehzpaul** [comment]
@earthstrider your solution would work but this would skip SSL verification of the server thereby defeating the purpose of HTTPS/a secure connection. I would personally not recommend using this option. Please try to use a better alternative for this problem. :)

**Comment by 0mza987** [comment]
Guys, here is the solution, just update 
`$ conda update anaconda-navigator`

Simple and works

**Comment by duyguay12** [comment]
I got SRE mismatched (AssertionError) before this CondaHTTPError. I followed below steps and now everything seems normal, anaconda navigator runs successfully.

You can check from **12 to 14** for the **CondaHTTPError**.

1. Uninstall the new anaconda installation.
2. Delete all the conda, anaconda files and folders on your computer. (They are located inside the C:\Users\<yourusername>, C:\Users\<yourusername>\Appdata\Local and C:\Users\<yourusername>\Appdata\Roaming folders).
3. Restart your computer.
4. Download the appropriate Miniconda installer. - https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe
5. Install it using the suggested settings.
6. Run the start menu shorcut Anaconda Prompt.
7. Execute the command `conda install anaconda anaconda-navigator` -> error.
8. Click Start,search "Edit the System environment variables". Click Environment Variables. Add the your path (C:\ProgramData\Miniconda3;C:\ProgramData\Miniconda3\Scripts) into the 'PATH' of "User Variables"
9. Run "`where conda`", it didn't worked.
10. `conda install anaconda anaconda-navigator`
	Error= SRE mismatched (AssertionError)-> i have upgraded the python from 3.7.0 to 3.7.3) because my conda uses 3.7.3. Run "`where conda`", it has worked then, it shows C:\ProgramData\Miniconda3\Scripts\conda.exe. Go there: cd C:\ProgramData\Miniconda3
12. `conda install anaconda anaconda-navigator`
	HTTPS and SSL error -> `conda config --set ssl_verify false` (check "`conda config --show`" = ssl_verify seems False)
13. `conda install anaconda anaconda-navigator`
    HTTPS and SSL error -> `conda config --set ssl_verify no` (check "`conda config --show`" = ssl_verify seems False)
14. `conda install anaconda anaconda-navigator`
	HTTPS and SSL error -> delete proxy_servers' values from condarc and save it. (it's path = C:\ProgramData\Miniconda3\pkgs\conda-4.6.14-py37_0\info\test\tests)
	Latest:
	"# Proxy settings: http://[username]:[password]@[server]:[port]
	proxy_servers:"
	Before:
	"# Proxy settings: http://[username]:[password]@[server]:[port]
	proxy_servers:
		http: http://user:pass@corp.com:8080
		https: https://user:pass@corp.com:8080"
15. `conda install anaconda anaconda-navigator` - started to downloading
16. Click Start, search Anaconda Navigator.

**Comment by kevin-keraudren** [comment]
> You really need to keep your SSL stack up-to-date. So
> 
> ```
> conda update openssl ca-certificates certifi
> ```

You can download the packages manually using your web browser, for instance:
https://anaconda.org/anaconda/openssl/files

Then install packages offline:
```
conda install --offline openssl-1.1.1c-he774522_1.tar.bz2
```

Updating `openssl` was enough for me to get the command-line installer back and running.

**Comment by gsibenik** [comment]
Had the same issue on Windows 7, for me worked replacing the DLLs in System32 from the Miniconda folder as described in [#8273](url).
Apparently the dlls from an old version were a problem.

**Comment by antoniogomes8** [comment]
> 
> 
> > After googling i got the solution for windows.
> > Ignore the _windows cmd_. Use **anaconda prompt**. It’s working.
> > [Ref...](http://www.probeqa.com/condahttperror-http-000-connection-failed/)
> 
> it's work for me.
> thx!

it's work for me

**Comment by voidwalker-M** [comment]
> Well the issue is most definitely NOT resolved for me. I'm NOT behind any firewall. I had a working installation of conda, until I did a "conda update conda". Immediately after that I got "Solving environment: failed" followed by this error. This happened once before, back in April or May. I had to completely uninstall Anaconda with all of the libraries I had collected, which took forever. And then reinstall from scratch. Since then I have been very careful NOT to "conda update conda", until today. So I'm not happy at the prospect of having to go through all that again, especially when the developers of conda apparently think that it's OUR problem.
> 
> Face it: the latest versions of conda are f'ed up. Please fix it.

same question!!

**Comment by aSquidsBody** [comment]
I had a similar problem that occurred practically anytime I tried to run a conda command. I couldn't update, install, create new envs, or download packages without running into the 

CondaHTTPError: HTTP 000 CONNECTION FAILED for URL ... (I don't rmember the url)

It turned out that the url was bad. I do not know how it got there, but it seemed out of place, so I went into my .condarc file, and removed it from the list of channels. Immediately, the errors went away and I could work as normal. I doubt my error had the same cause as your error, but to anyone reading this, I recommend checking the problem url and verifying that it is the correct one. If it is the correct url, then, naturally, the problem is elsewhere (for example, a cert problem or a proxy issue).

**Comment by adekability** [comment]
> One more thing... remember to include the following in your Path Variable....
> 
> D:\Anaconda3;
> D:\Anaconda3\Scripts;
> D:\Anaconda3\Library\bin
> 
> Most people tend to only add the first two ... as captured here.... [pypa/virtualenv#1139 (comment)](https://github.com/pypa/virtualenv/issues/1139#issuecomment-467705899)

@VictorOchieng! Your solution worked fine for me. Thank you very much!

**Comment by stevekm** [comment]
getting the same error, as described in my comment here: https://github.com/ContinuumIO/anaconda-issues/issues/6424

maybe I should have posted my comment in this thread though since it seems more active?

**Comment by stevekm** [comment]
Also this does not work:

```
root@0ddb969847b9:/# conda config --set ssl_verify no
root@0ddb969847b9:/# conda search -c conda-forge r-plotly
Loading channels: failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.continuum.io/pkgs/r/linux-64/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.continuum.io\', port=443): Max retries exceeded with url: /pkgs/r/linux-64/repodata.json.bz2 (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available.",))',),)
```
