### ISSUE TITLE
conda activate having issues on Windows 10

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#6597]
_From @dvincentwest on December 19, 2017 22:19_

I am on Windows 10 (Enterprise Laptop), which is a newish computer for me.

I can install and use Anaconda just fine, but creating new envs has run into a problem.  After first having this problem, I re-installed a fresh copy of Miniconda (latest) with no packages at all.  I then try to create a new env and then activate it, but I get a notice that 'B'  is not a recognized internal command. 

![image](https://user-images.githubusercontent.com/9872343/34181521-168ffa40-e4d8-11e7-9028-18c34b628525.png)

_Copied from original issue: ContinuumIO/anaconda-issues#7853_

**Comment by kalefranz** [comment]
Do you still have this problem with conda 4.4?

**Comment by dvincentwest** [comment]
sadly yes :-( .  If you have some suggestions about how to further pinpoint the problem I am happy to do some more investigation.

**Comment by kalefranz** [comment]
Start by sharing the output of ‘conda info’.

**Comment by dvincentwest** [comment]
```
Microsoft Windows [Version 10.0.14393]

A3R7LZZ@W0202248 C:\Users\A3R7LZZ
> conda info

     active environment : None
       user config file : C:\Users\A3R7LZZ\.condarc
 populated config files :
          conda version : 4.4.8
    conda-build version : not installed
         python version : 3.6.4.final.0
       base environment : C:\Miniconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\Miniconda3\pkgs
                          C:\Users\A3R7LZZ\AppData\Local\conda\conda\pkgs
       envs directories : C:\Miniconda3\envs
                          C:\Users\A3R7LZZ\AppData\Local\conda\conda\envs
                          C:\Users\A3R7LZZ\.conda\envs
               platform : win-64
             user-agent : conda/4.4.8 requests/2.18.4 CPython/3.6.4 Windows/10 Windows/10.0.14393
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by lovettchris** [comment]
In your screen shot above I see you had the error before you created your environment.  Did you try deleting your environment?  I wonder if your conda.bat got corrupted.  I've found that some bad packages can break conda.bat.  So check it looks the same is it does on your machines where conda is working fine.

**Comment by kalefranz** [comment]
We've addressed a similar problem in a related issue.  Can you pull conda 4.4.10 with `conda update conda` and see if we have it fixed for you?

**Comment by dvincentwest** [comment]
In the image please see what I have now after updating.

The left is the anaconda prompt which throws the error during startup.  I can use conda here, but I tried `conda install pyqtgraph` and it gave me the following error:

```
SafetyError: The package for pyqt located at C:\Miniconda3\pkgs\pyqt-5.6.0-py35hd46907b_5
appears to be corrupted. The path 'Lib/site-packages/PyQt5/uic/__pycache__/objcreator.cpython-35.pyc'
has a sha256 mismatch.
  reported sha256: a6845f527986f9c63b6778e26694f50a332580ac1662e110683668b44a64e59b
  actual sha256: 35be892f738e45c4d38b2b7ba326df3e1db9c00a11eef564c60ad203e3f4e05b
```

I don't know if this is a library path mismatch or what, but I've never seen that happen before.

On the right in the image below is a standard command line interface, which is still showing the same behavior as before

![image](https://user-images.githubusercontent.com/9872343/36165967-cefd2968-10b6-11e8-8bf9-8dbd09f3f779.png)

**Comment by kalefranz** [comment]
I guess I still need to lookin into what this `'B'` thing is.  Don't understand it yet.

**Comment by kalefranz** [comment]
The SafetyError you're encountering is likely from https://github.com/conda/conda/issues/6861

**Comment by dvincentwest** [comment]
Thought I would mention an update, through the anaconda prompt I am able to create and work with new envs, without any noticeable loss in functionality.  I do still see the 'b' warning on initial launch, but it doesn't seem to be hindering use.  Conda use through the main windows command line does still have some faults

![image](https://user-images.githubusercontent.com/9872343/40068960-845821a4-582f-11e8-9e3c-ceb3d81e0bdd.png)

**Comment by dvincentwest** [comment]
I am no longer having this issue at all

**Comment by dvincentwest** [comment]
I figured out what was causing this issue (I think)

I have SolidWorks installed on this computer and it has this entry in the path:

`C:\Program Files\R&B\R&B License Manager\App`

Something about setting the path is upset with this because of the `&` character. 

After escaping the `&` characters to `^&` this goes away.  Sorry for the trouble... I guess this is specific to me and anyone else with these things in their path

**Comment by dvincentwest** [comment]
> 
> 
> I guess I still need to lookin into what this `'B'` thing is. Don't understand it yet.

@kalefranz see my latest comment, very likely this issue can be closed
