### ISSUE TITLE
Can't connect to HTTPS URL because the SSL module is not available

### ISSUE THREAD

**Issue by SandorSzalma1** [conda/conda#8273]
## Current Behavior
Environment: Windows 2016 Server
Installer: https://repo.anaconda.com/archive/Anaconda3-2018.12-Windows-x86_64.exe

with the fresh installation neither conda nor pip are able to work

### Steps to Reproduce
Start Anaconda Prompt
`conda search conda` gives an error message:
**Can't connect to HTTPS URL because the SSL module is not available**

## Environment Information
 conda version : 4.5.12

## Resolution
I did a trace with Process Monitor.
D:\Anaconda3\DLLs\_ssl.pyd search for the OpenSSL DLLs but in the wrong/current location!
As they are not found the search goes to C:\Windows\System32 where we have the same DLLs, installed by an other application, but with a different version. :-(

The DLLs delivered by Anaconda3 are located here:
D:\Anaconda3\Library\bin

My workaround:
I have copied the following files
```
libcrypto-1_1-x64.*
libssl-1_1-x64.*
```
from D:\Anaconda3\Library\bin to D:\Anaconda3\DLLs.

And it works as a charm!

**Comment by msarahan** [comment]
Duplicate of https://github.com/conda/conda/issues/6064 - please see my comment at the end of that thread.

**Comment by ccoollavie** [comment]
Hi, 
Problem solved here ?
https://github.com/conda/conda/issues/8273
Copy these files from the ./Library/bin to ./DLL/ : 
libcrypto-1_1-x64.*
libssl-1_1-x64.*

**Comment by WRobertLong** [comment]
This worked for me. Thanks !

**Comment by robertcatgithub** [comment]
Thanks to SandorSzalma1
Downloaded & installed the latest miniconda  (Windows 64-bit,, Python 3.7) 
Dismayed to see this error when "conda update conda"

Do people not frigging test their software before release now ?

**Comment by msarahan** [comment]
We do.  We don't understand why people can't seem to follow the directions that we post for how to use it in ways that aren't broken, though.

If you use Anaconda Prompt, it works.  If you use activation manually somehow, it works.  If you ignore us about activation and PATH issues and assume that everything will be fine, odds are pretty good that it won't work.

**Comment by milkowski** [comment]
@msarahan I downloaded latest build of Miniconda 3 installer from https://docs.conda.io/en/latest/miniconda.html (as of this writing version 4.6.14) the issue is still there, after fresh installation on Windows `conda` is crashing with above error about SSL. With @SandorSzalma1 hack it works again. Update those installers ASAP and stop talking you resolved it already.

**Comment by mingwandroid** [comment]
Note, despite the comments here, nothing is nearly as broken as they commenters make out.

In fact the only ways I know of to get into trouble now is by installing 3rd party software that puts incompatible dlls in system directories and also having used `conda init` for a different install location.

For 1, that's not our fault, it's the 3rd parties fault (and yours for installing it but that's ok you weren't to know) but still we implemented a workaround. Set the environment variable CONDA_DLL_SEARCH_MODIFICATION_ENABLE. For 2, run <full_path_to_new_base_env_python.exe -m conda init` once only. You might need to set the env var above temporarily to be able to run this but that's not likely the case. This globalization of conda is troublesome to me, but we've not been recommending Windows users to use conda init yet so anyone doing that is following advice for other platforms.

**Comment by gluons** [comment]
Thank you very much. Your workaround work perfectly.

Windows symlink also work.  
```bat
mklink "C:\ProgramData\Anaconda3\DLLs\libcrypto-1_1-x64.dll" "C:\ProgramData\Anaconda3\Library\bin\libcrypto-1_1-x64.dll"
mklink "C:\ProgramData\Anaconda3\DLLs\libssl-1_1-x64.dll" "C:\ProgramData\Anaconda3\Library\bin\libssl-1_1-x64.dll"
```

**Comment by mingwandroid** [comment]
Thank for for the feedback @gluons. To everyone else on this thread, stop being offensive. There's never an excuse for that.
