### ISSUE TITLE
Warning about leaked semaphore under Python 3.8

### ISSUE THREAD

**Issue by mparry** [conda/conda#9589]
### Current Behavior
Under Python 3.8, there is a warning printed when running most conda commands:
```
~/miniconda3/lib/python3.8/multiprocessing/resource_tracker.py:216:
UserWarning: resource_tracker: There appear to be 1 leaked semaphore
objects to clean up at shutdown
```

### Steps to Reproduce
Running more or less any conda command will reproduce it for me, e.g. `conda env list`

## Expected Behavior
There should be no warning

## Environment Information
`conda-4.8.1-py38_0` and `python-3.8.1-h359304d_1` on MacOS (Catalina)

**Comment by jbieniasz** [comment]
Bump the issue as it still exists. I downgraded Python 3.8 to 3.7 at the base env to get rid off it.

**Comment by medley56** [comment]
This issue still exists. Any movement?

**Comment by NathanMoura** [comment]
same issue

**Comment by lhuaizhong** [comment]
same issue after updated to python 3.8.

**Comment by andrewsonin** [comment]
The same issue after updating the `base` environment to python 3.8.2.

**Comment by krishsandeep** [comment]
Get this only when I run:

`conda env list`

**Comment by ptoche** [comment]
conda env remove --name pypip
    /Users/username/miniconda3/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
    warnings.warn('resource_tracker: There appear to be %d '

    Remove all packages in environment /Users/username/miniconda3/envs/pypip:

**Comment by leeib3041** [comment]
This happened to me when creating and removing environments. This is the order I went in, more or less:
```
conda create --name py
conda create --name py3.8 python3.7
conda activate py3.8
conda update python
conda deactivate
conda activate     -----> this just activates (base)
conda env remove --name py
```
then that's when I got the error and I get it again every time I run `conda env list`
```
/opt/miniconda3/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
# conda environments:
#
base                  *  /opt/miniconda3
py3.8                    /opt/miniconda3/envs/py3.8

```

**Comment by hcygit** [comment]
encountering the same issue after upgrading to 3.8
only one base environment
please fix this annoying exception, thank you

**Comment by CodeLoe** [comment]
same issue

**Comment by faridn171** [comment]
same issue

**Comment by brando90** [comment]
> Bump the issue as it still exists. I downgraded Python 3.8 to 3.7 at the base env to get rid off it.

Did downgrading to python 3.7 remove this error for you? Just double checking.

**Comment by hcygit** [comment]
> > Bump the issue as it still exists. I downgraded Python 3.8 to 3.7 at the base env to get rid off it.
> 
> Did downgrading to python 3.7 remove this error for you? Just double checking.

for me it's true
at least no file resource_tracker.py in multiprocessing of 3.7

**Comment by oiwn** [comment]
same issue, fix it please.

**Comment by Jdbeck66** [comment]
Same issue - whenever I run conda env list

**Comment by yimingmao** [comment]
> same behavior for me here too...
> `conda env list`

same here

**Comment by psa-stanley** [comment]
same here

**Comment by mbwolff** [comment]
same here

**Comment by angloyna** [comment]
Looks related to locks in progress bar https://github.com/conda/conda/blame/master/conda/_vendor/tqdm/_tqdm.py#L69

**Comment by mparry** [comment]
Ah, good call - that does seem to be the issue. I'll open a PR.

**Comment by gloryVine** [comment]
Same problem

**Comment by mjsteinbaugh** [comment]
I can confirm I'm seeing this with full Anaconda 2020.07 install, which uses py38 conda 4.8.3
https://repo.anaconda.com/archive/Anaconda3-2020.07-Linux-x86_64.sh

**Comment by j0ner0n** [comment]
Confirm, issue persists

**Comment by angloyna** [comment]
👍 alright, I think we've got this covered. The python-3.8/conda-4.8.3 installers should still exhibit this warning, but we're shooting for a 4.8.4 release soon that should clear up the warning.

**Comment by sharmavaruns** [comment]
Not sure if I'm allowed to comment on a closed issue since I'm new to Github, but I got this semaphore error message when I installed Miniconda for Mac OS with Python 3.8 from the bash installation. However updating conda resolved the issue for me:

`conda update conda`

**Comment by angloyna** [comment]
@sharmavaruns of course, thanks for the update. We just released 4.8.4 with the fix, so you did the exact right thing.

**Comment by maguro** [comment]
Many thanks!  Is there an ETA for updated installers?

**Comment by angloyna** [comment]
We just released a set of installers, so it will be 4-5 months before we do another set, but if you run the conda update command, you’ll be able to fix the warning for the time being.

**Comment by taponidhitulsi** [comment]
Using `condo update --all` worked for me.

**Comment by erwanbou** [comment]
Use `conda update --all`

**Comment by gttiankai** [comment]
@erwanbou solve the works for me!

**Comment by Dastin346** [comment]
@saxenapawan800 Thanks, it works for me!

**Comment by EmanuelAlogna** [comment]
`condo update --all` worked also for me, thanks!

**Comment by sofialuma** [comment]
conda update --all worked for me as well! thanks all!

**Comment by samposn** [comment]
Line 216 is missing a “%"

![image](https://user-images.githubusercontent.com/9038545/96680188-a5611000-13a7-11eb-9ee8-33abf6b301a3.png)

**Comment by tongchao199** [comment]
conda update --all worked for me as well

**Comment by liujun1997** [comment]
> Use `conda update --all`

worked for me

**Comment by agnesia-lubuk** [comment]
> Use `conda update --all`

thanks! this works for me!

**Comment by yanqiangmiffy** [comment]
Yes install py37，it wil fix the problem！

**Comment by theoturner** [comment]
My program was failing with this error even after a full conda reinstall. The cause was actually a complex dataframe filter that resulted in a floating point error. For some reason this message got dumped, presumably because it was in a tqdm loop. If you have this issue, split your filtering into multiple stages.

**Comment by frortega** [comment]
lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

I reinstalled anaconda today, the did "conda update --all" a couple of times until no new updates were needed. This process left me with python 3.8.11 and the above warning (which hangs the current calculations). I tried downgrading to Python 3.8.10 and the same problem. 

Then i downgraded to python 3.8.8 (conda install python=3.8.8) and the problem was solved. So i deduct the bug was introduced in python 3.8.11 as no other packages were updated/downgraded when downgrading to python 3.8.8.

**Comment by scalastic** [comment]
Get the same error with python 3.8.13 
`lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 33 leaked semaphore objects to clean up at shutdown`
Downgraded to python 3.8.8 and still the same error...

**Comment by vantoniades** [comment]
same error for me:
`lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown                                                                                                                                                                                                                                  
  warnings.warn('resource_tracker: There appear to be %d '`
I'm running Python 3.8.13 on MacOs on a conda env.

**Comment by TacoByte** [comment]
same here `/opt/anaconda3/envs/ldm/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '`

**Comment by udaylunawat** [comment]
This issue persists on M1 Macbook Air (8 GB RAM)

python versions - 3.8, 3.9, 3.10.6
tensorflow-metal 0.6
tensorflow-macos 2.9

MacOS 12.6

```bash
Metal device set to: Apple M1

systemMemory: 8.00 GB
maxCacheSize: 2.67 GB

2022-10-28 23:22:55.313576: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-10-28 23:22:55.314284: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
Found 301 files belonging to 7 classes.
Found 311 files belonging to 7 classes.
[1]    90708 bus error  python src/models/train.py wandb.mode=offline batch_size=4
/Users/uday/miniforge3/envs/rocks/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by zhanwenchen** [comment]
I got this error while running `tqdm=4.65.0`. I was able to remove it and install 4.66.1 which solved it. Not a RAM issue.

**Comment by volod-vana** [comment]
I reused Virtual Environment under the Automatic 1111 installation directory and had the same issue on mac M2. What solved it for me is uninstalling Torch 2.0.1 then I installed nightly version of Tourch.

```bash
pip3 uninstall torch
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu
```

**Comment by LukaVerhoeven** [comment]
Rebooting my devices fixed the issue...
